### PR TITLE
New function version_info(): Displays the current version number of JamDB Oracle.

### PR DESCRIPTION
**Pull request by walter-weinmann**
Resolves issue #73.

### CODE REVIEW

**Comment by vstavskyi** [comment]
Do any of ecto/elixir/erlang database drivers have this function?

**Comment by walter-weinmann** [comment]
I think it is generally very polite to provide your own version number at runtime.

I am currently working on a project that wants to show the performance of different Oracle database drivers in combination with suitable programming languages (see: https://github.com/KonnexionsGmbH/ora_bench). One of the driver candidates is `jamdb_oracle`. With the measurement results I would like to document the used versions of the database drivers and programming languages.

**Comment by vstavskyi** [comment]
Why don't you like `vsn` module attribute?

**Comment by walter-weinmann** [comment]
image

Then you have to maintain the same information in two different places - that looks very error-prone to me.

**Comment by vstavskyi** [comment]
It's OK for me to do this.

**Comment by walter-weinmann** [comment]
Why didn't you merge it ?

**Pull request closed without merging**
