### PR TITLE
Handle TNS redirect

### PR DESCRIPTION
**Pull request by cdinger**
This parses the TNS_REDIRECT and subsequent TNS_DATA packet to properly handle a redirect.

This PR also updates the version of the `erlang-jose` dependency to `1.8.0` (I couldn't get this to build under `1.4.2`).

Big disclaimer: I'm new to Erlang. I'm not sure how idiomatic any of this is, so feedback is more than welcome! My goal is to connect to Oracle databases from Elixir and my employer uses TNS redirection, so handling this case is necessary for me.

/cc @davinlagerroos

### CODE REVIEW

**Comment by vstavskyi** [comment]
My employer don't use any listener with redirection. Could you pls paste here dump of request and response packets in pcap or raw. I'd like to code redirection without re module.

**Comment by cdinger** [comment]
Thanks for looking at this, @vstavskyi! I agree the regex is not ideal.

I've attached three packets:

1. the initial connection
2. the TNS_REDIRECT
3. the following TNS_DATA packet with the redirect details

I've obscured some of the data in the example (IPs, hostnames, schema names) but I've made sure to keep the packet sizes the same.

Based on some of the documentation I've found, TNS_REDIRECT will sometimes supply the redirect details in the TNS_REDIRECT packet itself but I've never actually seen this happen. This might only occur on certain setups or when the redirect data is shorter.

The redirect data appears to contain two TNS strings: one with just a host (I think this is intended as the host for re-establishing the TCP connection) and one with the TNS string to connect with.

[tns_redirect_example.pcapng.zip](https://github.com/erlangbureau/jamdb_oracle/files/711865/tns_redirect_example.pcapng.zip)

**Comment by vstavskyi** [comment]
So, we must replace host and port in our connection string (DESCRIPTION=(CONNECT_DATA=...  with data from first part of response:  (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host)(PORT=port)))

**Comment by cdinger** [comment]
> So, we must replace host and port in our connection string (DESCRIPTION=(CONNECT_DATA=... with data from first part of response: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host)(PORT=port))).

I believe that's correct. That approach works in our environment.

**Comment by vstavskyi** [comment]
Please test that redirecting works after my last commit.

**Comment by cdinger** [comment]
@vstavskyi it works great. Many thanks for these changes!

**Pull request closed without merging**
