### PR TITLE
Fix/missing packets

### PR DESCRIPTION
**Pull request by kagux**
WIP for #22 

The idea is to check for next packet if last one had max size. Couple issues in this PR:
* max size is hardcoded, any way I can get this number for current environment
* timeout to check for next packet is hardcoded, not sure the best way to pass it

Anyway, this is more to show you the idea, you might have a better way of implementing this, I'm new to erlang.

### CODE REVIEW

**Comment by vstavskyi** [comment]
Your changes were failed without timer:sleep, but so were mine.

Could you please test original version (see below) with different Time in  timer:sleep.
For me Time of 10 is low enough.


```
recv(Socket, Tout) ->
    recv(Socket, <<>>, <<>>, Tout).
	
recv(Socket, Data, Acc, Tout) ->
	case sock_recv(Socket, 0, Tout) of
        {ok, NetworkData} ->
	%%%%  timer:sleep(10),
	      PacketBody = <<Acc/bits, NetworkData/bits>>,
	      recv(Socket, decode_packet(PacketBody), Data, PacketBody, Tout);
        {error, Reason} ->
            {error, socket, Reason}
    end.

recv(Socket, {?TNS_DATA, 0, Rest}, Data, Acc, Tout) ->
	try decode_packet(Rest) of
		{?TNS_DATA, Length, _Rest} ->  recv(Socket, {?TNS_DATA, Length, Rest}, Data, Rest, Tout)
	catch
		error:_ -> {ok, ?TNS_DATA, <<Data/bits, Rest/bits>>}
    end;
recv(_Socket, {Type, 0, Rest}, Data, _Acc, _Tout) ->
	{ok, Type, <<Data/bits, Rest/bits>>};
recv(Socket, {_Type, Length, Rest}, Data, Acc, Tout) when Length < 0 ->
	recv(Socket, <<Data/bits, (binary:part(Rest,0,byte_size(Rest)+Length))/bits>>,
							   binary:part(Acc,byte_size(Acc),Length), Tout);
recv(Socket, {_Type, _Length, _Rest}, Data, Acc, Tout) ->
	recv(Socket, Data, Acc, Tout).

decode_packet(<<PacketSize:16, 0:16, ?TNS_DATA, _Flags:8, 0:16, _DataFlags:16, Rest/bits>>) ->
	{?TNS_DATA, PacketSize - byte_size(Rest) - 10, Rest};
decode_packet(<<PacketSize:16, 0:16, Type, _Flags:8, 0:16, Rest/bits>>) ->
	{Type, PacketSize - byte_size(Rest) - 8, Rest}.


```


```
recv(Socket, Tout) ->
    recv(Socket, Tout, <<>>, <<>>).

recv(Socket, Tout, Acc, Data) ->
    case ?DECODER:decode_packet(Acc) of
        {ok, Type, PacketBody, <<>>} ->
            {ok, Type, <<Data/bits, PacketBody/bits>>};
        {ok, _Type, PacketBody, Rest} ->
            recv(Socket, Tout, Rest, <<Data/bits, PacketBody/bits>>);
        {error, more} ->
            case sock_recv(Socket, 0, Tout) of
                {ok, NetworkData} ->
		    timer:sleep(10),
                    recv(Socket, Tout, <<Acc/bits, NetworkData/bits>>, Data);
                {error, Reason} ->
                    {error, socket, Reason}
            end
    end.

```

**Comment by kagux** [comment]
I don't think sleeping is the right approach. It depends on connection quality and it's hard to estimate correctly the value. On top of that, it adds delay to every data packet instead of only problematic big packets.
The reason my changes might fail could be max size, that probably system dependant and should be read from env. 

By the way, we've been using PR branch in production for 2 weeks without single issue.

**Comment by vstavskyi** [comment]
I found two magic sizes for packets: 8155 and 8111.
If size of the last data packet is 8155 or 8111, then we receive one more packet with TTI_RPA and TTI_OER.
Please test this fix.
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/5d706a774c7a0ca0f7d1bc973a8c0d154e3369bf)
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/97f52c6e144742c30f16de06bd35e3d1860e61b2)

**Comment by kagux** [comment]
thanks to your latest updates, this is no longer relevant

**Pull request closed without merging**
